// server//appwrite-server.ts
import { Client, Account, Users, Databases, Query, ID } from "node-appwrite";
import { EVALUATION_COLLECTION_DEFAULTS, getServerAppwriteConfig, lazyService } from "@/lib/config/environment";

const createServerClient = () => {
  const config = getServerAppwriteConfig()
  return new Client().setEndpoint(config.endpoint).setProject(config.projectId).setKey(config.apiKey)
}

export const serverClient = lazyService(createServerClient);
export const users = lazyService(() => new Users(createServerClient()));
export const serverAccount = lazyService(() => new Account(createServerClient()));
export const databases = lazyService(() => new Databases(createServerClient()));

// Export server-safe query utilities
export { Query, ID };

// Server-side safe configuration evaluation
export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID ?? "";

export const COLLECTIONS = {
  USERS:         process.env.COLLECTION_USERS!,
  QUERIES:       process.env.COLLECTION_QUERIES!,
  SNAPSHOTS:     process.env.COLLECTION_SNAPSHOTS!,
  FEEDBACK:      process.env.COLLECTION_FEEDBACK!,
  ANALYTICS:     process.env.COLLECTION_ANALYTICS!,
  NOTIFICATIONS: process.env.COLLECTION_NOTIFICATIONS!,
  ACCESS_LOGS:   process.env.NEXT_PUBLIC_COLLECTION_ACCESS_LOGS!,
  API_USAGE:     process.env.COLLECTION_API_USAGE!,
  SETTINGS:      process.env.NEXT_PUBLIC_COLLECTION_SETTINGS!,
  EVALUATION_DATASETS: process.env.COLLECTION_EVALUATION_DATASETS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_DATASETS,
  EVALUATION_QUERIES: process.env.COLLECTION_EVALUATION_QUERIES ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_QUERIES,
  EVALUATION_QUERY_CONFIGS: process.env.COLLECTION_EVALUATION_QUERY_CONFIGS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_QUERY_CONFIGS,
  RELEVANCE_JUDGMENTS: process.env.COLLECTION_RELEVANCE_JUDGMENTS ?? EVALUATION_COLLECTION_DEFAULTS.RELEVANCE_JUDGMENTS,
  RELEVANCE_JUDGMENT_PAYLOADS: process.env.COLLECTION_RELEVANCE_JUDGMENT_PAYLOADS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_JUDGMENT_PAYLOADS,
  EVALUATION_PAYLOAD_CHUNKS: process.env.COLLECTION_EVALUATION_PAYLOAD_CHUNKS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_PAYLOAD_CHUNKS,
  EVALUATION_RUNS: process.env.COLLECTION_EVALUATION_RUNS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_RUNS,
  EVALUATION_RUN_QUERIES: process.env.COLLECTION_EVALUATION_RUN_QUERIES ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_RUN_QUERIES,
  EVALUATION_STAGE_TRACES: process.env.COLLECTION_EVALUATION_STAGE_TRACES ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_STAGE_TRACES,
  EVALUATION_STAGE_TRACE_DOCUMENTS: process.env.COLLECTION_EVALUATION_STAGE_TRACE_DOCUMENTS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_STAGE_TRACE_DOCUMENTS,
  EVALUATION_STRATEGIES: process.env.COLLECTION_EVALUATION_STRATEGIES ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_STRATEGIES,
  EVALUATION_STRATEGY_EXECUTIONS: process.env.COLLECTION_EVALUATION_STRATEGY_EXECUTIONS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_STRATEGY_EXECUTIONS,
  EVALUATION_STRATEGY_EXECUTION_DOCUMENTS: process.env.COLLECTION_EVALUATION_STRATEGY_EXECUTION_DOCUMENTS ?? EVALUATION_COLLECTION_DEFAULTS.EVALUATION_STRATEGY_EXECUTION_DOCUMENTS,
};
